# Generated by Django 4.1.7 on 2023-04-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='re_password',
            field=models.CharField(max_length=128, null=True, verbose_name='re-password'),
        ),
    ]
